[{
  experiments : { 0: [[]],
                  11: [[], [0]],
                  12: [[], [0], [1]],                
                  13: [[], [0], [1], [2]],
                  14: [[], [0], [1], [2], [3]],
                  15: [[], [0], [1], [2], [3], [4]],
                  21: [[], [0, 1]],
                  22: [[], [0, 1], [1, 2]],
                  23: [[], [0, 1], [1, 2], [2, 3]],
                  24: [[], [0, 1], [1, 2], [2, 3], [3, 4]],
                  25: [[], [0, 1], [1, 2], [2, 3], [3, 4], [4, 0]],
                  31: [[], [0, 1, 2]],
                  32: [[], [0, 1, 2], [1, 2, 3]],
                  33: [[], [0, 1, 2], [1, 2, 3], [2, 3, 4]],
                  34: [[], [0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 0]],
                  35: [[], [0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 0], [4, 0, 1]],
                  41: [[], [1,2,3,4]],
                  42: [[], [1,2,3,4], [0,2,3,4]],
                  43: [[], [1,2,3,4], [0,2,3,4], [0,1,3,4]],
                  44: [[], [1,2,3,4], [0,2,3,4], [0,1,3,4], [0,1,2,4]],
                  45: [[], [1,2,3,4], [0,2,3,4], [0,1,3,4], [0,1,2,4], [0,1,2,3]]},           
  n_obs: 5,
  n_conf: 2, 
  n_samples: [1_000, 10_000, 100_000, inf], 
  cyclic: True, 
  name: 'hyperparameter_eval', 
  lB: 0, 
  uB: 2, 
  seps: ['s', 'd'],             # ASP-s encoding and ASP-d encodings
  asp_modes: [3],               # run ASP to get confidence values
  alpha_asp: 0.05,              # significance level ASP
  faithful_modes: [0,1],        # LLC-F and LLC-NF
  llc_mode: 2,                  # bootstrapping LLC 
  penalty: 'L1',                # 'L1' penalty
  reg: 0.05,                    # regularization parameter
  alpha_llc: 0.05,              # significance level LLC
  rules: [1,2,3]                # use all 3 faithfulness rules
  }
]