# # The following python code was used to generate this yaml file:
# #
# import yaml
# import random

# def generate_exp(n_intervenions, n_exp, n_vars):
#     """
#     Function takes three integer arguments n_interventions, n_exp, and n_vars to return a list of sublists.
#     Each sublist contains n_interventions integers in the range(0, n_vars). The function generates a total of n_exp
#     sublists with each sublist randomly sampled to ensure that no two sublists are identical.

#     @param n_interventions: An integer representing the number of interventions in each sublist.
#     @param n_exp: An integer representing the total number of sublists to be generated.
#     @param n_vars: An integer representing the upper limit of the range to sample from.

#     @return: A list of sublists where each sublist contains n_interventions integers within the range
#     """
#     exp = []
#     while len(exp) != n_exp:
#         setup = random.sample(range(n_vars), n_intervenions)
#         if sorted(setup) not in [sorted(i) for i in exp]: 
#             exp.append(setup)
#     return exp


# if __name__ == '__main__':
    
#     confs = [{
#             'experiments' : {'1': [[i] for i in random.sample(range(5), 3)],
#                              '2': generate_exp(3, 3, 5)},            
#             'n_obs': 5,
#             'n_conf': 2, 
#             'n_samples': [1_000, 10_000], 
#             'cyclic': True, 
#             'name': f'optuna_llc_f_l2', 
#             'lB': 0, 
#             'uB': 2, 
#             'seps': [],
#             'asp_modes': [],        # does not run any ASP-modes
#             'llc_mode': 2,          # bootstrapped version to calculate z-scores
#             'penalty': 'L2',        # L2-norm for LLC regularization 
#             'faithful_modes': [1],  # with additional faithfulness rules
#             'rules': [1,2,3]        # use all 3 faithfulness rules
#             } for _ in range(25)]

#     with open('./config/optuna_llc_f_l2.yml', 'w') as stream:
#       stream.write(yaml.dump(confs))

- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 2
    - - 3
    - - 0
    '2':
    - - 4
      - 3
      - 2
    - - 4
      - 0
      - 3
    - - 0
      - 4
      - 1
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 4
    - - 3
    - - 0
    '2':
    - - 1
      - 2
      - 0
    - - 1
      - 4
      - 2
    - - 4
      - 3
      - 0
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 1
    - - 4
    - - 3
    '2':
    - - 4
      - 1
      - 3
    - - 0
      - 4
      - 1
    - - 1
      - 4
      - 2
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 1
    - - 4
    - - 0
    '2':
    - - 1
      - 3
      - 0
    - - 0
      - 2
      - 4
    - - 2
      - 3
      - 0
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 2
    - - 0
    - - 4
    '2':
    - - 1
      - 0
      - 4
    - - 4
      - 3
      - 1
    - - 1
      - 2
      - 4
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 1
    - - 0
    - - 4
    '2':
    - - 2
      - 0
      - 1
    - - 4
      - 1
      - 2
    - - 0
      - 4
      - 2
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 0
    - - 2
    - - 4
    '2':
    - - 2
      - 0
      - 4
    - - 0
      - 1
      - 3
    - - 4
      - 2
      - 1
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 1
    - - 4
    - - 2
    '2':
    - - 0
      - 2
      - 4
    - - 1
      - 0
      - 4
    - - 4
      - 2
      - 1
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 3
    - - 2
    - - 1
    '2':
    - - 1
      - 0
      - 2
    - - 4
      - 0
      - 3
    - - 4
      - 1
      - 2
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 1
    - - 2
    - - 3
    '2':
    - - 4
      - 0
      - 3
    - - 1
      - 4
      - 0
    - - 2
      - 3
      - 4
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 4
    - - 3
    - - 0
    '2':
    - - 4
      - 3
      - 2
    - - 2
      - 3
      - 0
    - - 0
      - 3
      - 4
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 1
    - - 0
    - - 3
    '2':
    - - 1
      - 4
      - 0
    - - 3
      - 1
      - 0
    - - 4
      - 0
      - 2
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 0
    - - 3
    - - 1
    '2':
    - - 3
      - 2
      - 1
    - - 4
      - 0
      - 1
    - - 1
      - 0
      - 3
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 3
    - - 2
    - - 0
    '2':
    - - 2
      - 3
      - 0
    - - 3
      - 0
      - 4
    - - 0
      - 2
      - 1
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 2
    - - 4
    - - 3
    '2':
    - - 4
      - 0
      - 2
    - - 2
      - 1
      - 0
    - - 3
      - 2
      - 0
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 1
    - - 3
    - - 4
    '2':
    - - 4
      - 0
      - 3
    - - 2
      - 1
      - 0
    - - 2
      - 3
      - 4
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 1
    - - 2
    - - 0
    '2':
    - - 1
      - 3
      - 4
    - - 3
      - 4
      - 0
    - - 3
      - 1
      - 0
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 2
    - - 4
    - - 0
    '2':
    - - 1
      - 2
      - 0
    - - 3
      - 4
      - 2
    - - 0
      - 4
      - 2
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 3
    - - 4
    - - 2
    '2':
    - - 4
      - 3
      - 1
    - - 1
      - 0
      - 2
    - - 1
      - 3
      - 2
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 2
    - - 0
    - - 3
    '2':
    - - 1
      - 3
      - 4
    - - 1
      - 0
      - 2
    - - 4
      - 0
      - 1
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 1
    - - 3
    - - 0
    '2':
    - - 1
      - 4
      - 0
    - - 1
      - 3
      - 2
    - - 3
      - 0
      - 1
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 4
    - - 3
    - - 2
    '2':
    - - 2
      - 0
      - 3
    - - 2
      - 4
      - 1
    - - 1
      - 0
      - 2
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 4
    - - 2
    - - 1
    '2':
    - - 2
      - 4
      - 3
    - - 4
      - 0
      - 2
    - - 4
      - 3
      - 0
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 4
    - - 0
    - - 3
    '2':
    - - 0
      - 1
      - 3
    - - 0
      - 3
      - 2
    - - 3
      - 4
      - 2
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
- asp_modes: []
  cyclic: true
  experiments:
    '1':
    - - 3
    - - 2
    - - 1
    '2':
    - - 2
      - 3
      - 1
    - - 1
      - 0
      - 2
    - - 0
      - 3
      - 4
  faithful_modes:
  - 1
  lB: 0
  llc_mode: 2
  n_conf: 2
  n_obs: 5
  n_samples:
  - 1000
  - 10000
  name: optuna_llc_f_l2
  penalty: L2
  rules:
  - 1
  - 2
  - 3
  seps: []
  uB: 2
